[0m16:23:06.420610 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000212D194C830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000212D194C3B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000212D194C2F0>]}


============================== 16:23:06.425619 | 58ade357-2618-4ad0-8b7c-642257282428 ==============================
[0m16:23:06.425619 [info ] [MainThread]: Running with dbt=1.7.9
[0m16:23:06.426138 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\sulta\\Desktop\\Python\\DBT\\DBT_introduction\\DBT-Introduction', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:23:06.427249 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\sulta\Desktop\Python\DBT\DBT_introduction\DBT-Introduction\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:23:06.429259 [debug] [MainThread]: Command `dbt run` failed at 16:23:06.429259 after 0.16 seconds
[0m16:23:06.429770 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000212D15A3140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000212D1983A40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000212D1983D10>]}
[0m16:23:06.429770 [debug] [MainThread]: Flushing usage events
[0m16:23:58.955769 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B06FE5C5F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B06FE5C590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B06FE5C4D0>]}


============================== 16:23:58.963419 | 3006981a-bc7b-4ed3-8871-a4d45957ff9a ==============================
[0m16:23:58.963419 [info ] [MainThread]: Running with dbt=1.7.9
[0m16:23:58.964371 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\sulta\\Desktop\\Python\\DBT\\DBT_introduction\\DBT-Introduction', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt test --select stg_customers.yml', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m16:23:58.965396 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\sulta\Desktop\Python\DBT\DBT_introduction\DBT-Introduction\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:23:58.967387 [debug] [MainThread]: Command `dbt test` failed at 16:23:58.967387 after 0.16 seconds
[0m16:23:58.968388 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B06FD4F230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B06FE8E690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B06FE8FB90>]}
[0m16:23:58.969301 [debug] [MainThread]: Flushing usage events
[0m16:24:54.141231 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ECC94C9B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ECC504C50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ECC94C560>]}


============================== 16:24:54.145206 | b5500cd9-1387-4708-957e-3e67c57e61f7 ==============================
[0m16:24:54.145206 [info ] [MainThread]: Running with dbt=1.7.9
[0m16:24:54.146207 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\sulta\\Desktop\\Python\\DBT\\DBT_introduction\\DBT-Introduction', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'C:\\Users\\sulta\\Desktop\\Python\\DBT\\DBT_introduction\\DBT-Introduction\\logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt test --select stg_customers.yml', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:24:54.301601 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'b5500cd9-1387-4708-957e-3e67c57e61f7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ECC830470>]}
[0m16:24:54.366744 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'b5500cd9-1387-4708-957e-3e67c57e61f7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ECCA68B30>]}
[0m16:24:54.367577 [info ] [MainThread]: Registered adapter: mysql=1.7.0
[0m16:24:54.374125 [debug] [MainThread]: checksum: 6ff0d83c3b46f350064523b4e08d9241403ad71d606ba49c4e670afba3668b39, vars: {}, profile: , target: , version: 1.7.9
[0m16:24:54.375111 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m16:24:54.376111 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'b5500cd9-1387-4708-957e-3e67c57e61f7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ECC97FD40>]}
[0m16:24:54.783964 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.dbt_project.staging
[0m16:24:54.789466 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'b5500cd9-1387-4708-957e-3e67c57e61f7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ECD236510>]}
[0m16:24:54.800456 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'b5500cd9-1387-4708-957e-3e67c57e61f7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ECD2E9DC0>]}
[0m16:24:54.801462 [info ] [MainThread]: Found 0 sources, 0 exposures, 0 metrics, 375 macros, 0 groups, 0 semantic models
[0m16:24:54.802463 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'b5500cd9-1387-4708-957e-3e67c57e61f7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ECD2B8200>]}
[0m16:24:54.803477 [warn ] [MainThread]: The selection criterion 'stg_customers.yml' does not match any nodes
[0m16:24:54.806450 [info ] [MainThread]: 
[0m16:24:54.806450 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m16:24:54.807447 [debug] [MainThread]: Command end result
[0m16:24:54.816969 [debug] [MainThread]: Command `dbt test` succeeded at 16:24:54.815965 after 0.79 seconds
[0m16:24:54.816969 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ECC97F800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ECC97FA10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ECC97F950>]}
[0m16:24:54.817987 [debug] [MainThread]: Flushing usage events
